### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [JasonShueh/firehose_1#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by JasonShueh** [comment]
Will do Ken, thanks for the assist.

**Comment by JasonShueh** [comment]
@kenmazaika Hi Ken, thanks for the finishing touch, added the mobile meta tag to the header with this code I found online.  **meta name="viewport" content="width=device-width"** Think it did the trick.

**Comment by kenmazaika** [comment]
Looks great! :) :+1:
